python run.py \
--gpu 0 \
--data_path ./aircraft_npys \
--loader AirCraft \
--task steady_cond \
--dynamics craft \
--geotype unstructured \
--space_dim 3 \
--fun_dim 10 \
--out_dim 6 \
--normalize 1 \
--model Transolver \
--n_hidden 256 \
--n_heads 8 \
--n_layers 8 \
--mlp_ratio 2 \
--slice_num 32 \
--ntrain 100 \
--ntest 50 \
--batch-size 1 \
--epochs 200 \
--eval 0 \
--save_name craft_transolver_8layers_normal_cond

