python run.py \
--gpu 1 \
--data_path ./nasa_npys \
--loader NASA \
--task GeoPT_finetune \
--dynamics nasa \
--geotype unstructured \
--space_dim 3 \
--fun_dim 11 \
--out_dim 1 \
--normalize 0 \
--model Transolver \
--n_hidden 256 \
--n_heads 8 \
--n_layers 8 \
--mlp_ratio 2 \
--slice_num 32 \
--ntrain 105 \
--ntest 44 \
--batch-size 1 \
--epochs 200 \
--eval 0 \
--save_name nasa_transolver_8layers_geopt_cond

